### ISSUE TITLE
Link in docs broken

### ISSUE THREAD

**Issue by devmozao** [TanStack/config#17]
### Describe the bug

Link on docs are broken when you open the repository (an article brought me to the repo directly, and when you see the link on the readme, is broken.

![image](https://github.com/TanStack/config/assets/15485768/1f75d612-1ea1-4db9-9400-0a899d0a8103)

### Steps to reproduce

Just go to the repo and open the link into the readme.

### Expected behavior

Open the docs correctly to see whats the repo is all about.

### How often does this bug happen?

None

### TanStack Config version

v0.1.3

**Comment by crutchcorn** [comment]
This is known. For now, please check our docs folder:

https://github.com/TanStack/config/tree/main/docs

**Comment by crutchcorn** [comment]
This should now be fixed!
